Use units registry provided by `openff.units`
openforcefield/openff-evaluator pull request #399
Opened 2021-11-08 18:57 UTC by mattwthompson

Resolves #398 

I've split this up into two steps: 515f6df53f8e47e71913dea46deccaf57576a7bc is the meat of the change and 512482579e06d69799aeb7d9d8dca5296fce6518 attempts to remove all `from openff.evaluator import unit`; while not strictly necessary, it'd need to happen eventually.

2021-11-08 18:58 UTC, mattwthompson commented on openff/evaluator/__init__.py
> +
This arguably should be dropped altogether, though it would break some amount of backwards compatibility.

2021-11-09 20:57 UTC, mattwthompson commented on devtools/conda-envs/test_env.yaml
> +    - git+https://github.com/openforcefield/openff-units.git@openmm-dalton
This is https://github.com/openforcefield/openff-units/pull/11; my plan is as follows:

1. Get this passing and provisionally approved
2. Merge that PR
3. Make a new release of `openff-units`
4. Update pins here as needed
5. Aim to merge this PR

2021-11-22 15:31 UTC, mattwthompson commented
Could I get another review @SimonBoothroyd @jeff231li? At least to get through step 1 [above](https://github.com/openforcefield/openff-evaluator/pull/399#discussion_r746034311) so I don't need to go through 2+ releases of `openff-units`.

2021-11-22 15:37 UTC, SimonBoothroyd requested changes
LGTM once the CI is switched back to a conda package after a new `openff-units` release

2021-11-22 20:55 UTC, mattwthompson commented
Looks like everything is passing with `openff-units` v0.1.4!

2021-11-23 14:51 UTC, SimonBoothroyd approved these changes
LGTM - thanks @mattwthompson

2021-11-23 14:54 UTC, merged

2022-04-11 00:05 UTC, lilyminium commented
FYI, ForceBalance imports `openmm_quantity_to_pint` so a similar change might be needed there for the next release :-)